# Read the configuration file
configfile: "config.yaml"

file_of_batches = config["file_of_batches"]
output_dir = config["output_dir"]

# Read the single .txt file to get the list of all input files
with open(file_of_batches,"r") as f:
    batches = [line.strip() for line in f]

# Get the batch numbers based on the line indices in the input file
batch_numbers = range(len(batches))


rule all:
    input:
        expand(f"{output_dir}/batch_{{i}}", i=batch_numbers)


rule extract_assemblies:
    input:
        input_file=lambda wildcards: batches[int(wildcards.i)]
    output:
        output_dir=directory(f"{output_dir}/batch_{{i}}")
    threads: 1
    resources: mem_mb=2000
    log: "logs/extract_assemblies/batch_{i}.log"
    shell:
        "python extract_assemblies.py -i {input.input_file} -o {output.output_dir} 2>{log}"
